      SUBROUTINE RELEM
C
C---- READ IN ELEMENT CONNECTIVITY
C
      COMMON /CONTR/NNODE,NELEM
      COMMON /ELEM/NODE(8,2000)

      READ(5,*) NELEM
      DO 50 NR=1,NELEM
        READ(5,*) ELNUM,NODE(1,NR),NODE(2,NR),NODE(3,NR),NODE(4,NR),
     1   NODE(5,NR),NODE(6,NR),NODE(7,NR),NODE(8,NR)  
50    CONTINUE
C
C     PRINT OUT ELEMENT CONNECTIVITY
C

      RETURN
      END