      SUBROUTINE RNODE
C
C---- READ IN NODAL POINT DATA
C
      COMMON /CONTR/NNODE,NELEM
      COMMON /NODES/X(3,4000)
      READ(5,*) NNODE
      DO 30 NR=1,NNODE
      READ(5,*) N,X(1,NR),X(2,NR),X(3,NR)
30    CONTINUE
C
C---- PRINT OUT NODAL POINT COORDINATES
C

      RETURN
      END