      SUBROUTINE RELEM
C
C---- READ IN ELEMENT CONNECTIVITY
C
      COMMON /CONTR/NNODE,NELEM
      COMMON /ELEM/NODE(8,2000)

      READ(5,*) NELEM
      DO 50 NR=1,NELEM
        READ(5,*) ELNUM,NODE(1,NR),NODE(2,NR),NODE(3,NR),NODE(4,NR),
     1   NODE(5,NR),NODE(6,NR),NODE(7,NR),NODE(8,NR)  
50    CONTINUE
C
C     PRINT OUT ELEMENT CONNECTIVITY
C
      WRITE(6,55)
55    FORMAT(/2X,'ELEMENT CONNECTIVITY :'/)
      DO 60 I=1,NELEM
        WRITE(6,200) I,(NODE(J,I),J=1,8)
200     FORMAT(5X,'ELEMENT #',I4,3X,'NODES=',4I5)
60    CONTINUE

      RETURN
      END